### PR TITLE
Mostly formatting of CMake files. Added examples folder.

### PR DESCRIPTION
**Pull request by gvanhoy**

### CODE REVIEW

**Comment by skoslowski** [comment]
Did use an auto-formattor for your cmake changes? Just curious why there's spaces separating commands from their parentheses

**Comment by gvanhoy** [comment]
> Did use an auto-formattor for your cmake changes? Just curious why there's spaces separating commands from their parentheses

Yes. I could not quite get the formatter to do everything I preferred, but I figured that'd be a work in progress anyway.

**Comment by mormj** [comment]
@gvanhoy - i've got some other changes i want to merge onto modular shortly - since it looks like most of the changes are automated formatter, can you make a separate PR for the substantive changes, then we can do the formatting after the other changes are merged?

**Comment by gvanhoy** [comment]
@mormj To be more clear, there is nothing substantive here. This is literally only formatting changes here (plus a cmake-format file) so I'm pretty confident this would not be a difficult or impactful merge. 

I just see myself formatting files as we go along anyway and would just like to avoid formatting locally and then un-formatting before I commit so that actual changes are clear. Git pre-hooks helps solve this problem, but I have not set them up before.

If it's easier, this could be done manually after the changes you are working on are merged here as you mention.

**Comment by gvanhoy** [comment]
Closing -- will make a new one if necessary.

**Pull request closed without merging**
